apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: music-store-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - musicstore.example.com
    secretName: music-store-tls
  rules:
  - host: musicstore.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: music-store-service
            port:
              number: 80
